### PR TITLE
Remove training plotter & update readme

### PR DESCRIPTION
**Pull request by Curt-Park**
#### Structured Pruning + LTH
1. L2 Magnitude
2. Slim
3. L2 Magnitude + Slim

Screen Shot 2020-08-26 at 11 05 22 PM

#### Unstructured Pruning
1. LTH
2. LR Rewinding

Screen Shot 2020-08-24 at 1 00 31 AM

https://app.wandb.ai/j-marple/model_compression/reports/Structured-Pruning-Unstructured-Pruning--VmlldzoyMTA4MDA

### CODE REVIEW

**Comment by Curt-Park** [comment]
`PRUNE_START_FROM` -> `TRAIN_START_FROM`

**Comment by Curt-Park** [comment]
Slim 19.66% pruned

parameters

```bash
2020-08-26 13:50:38,442 - trainer.py:71 - INFO - Created a model densenet with 0.78M params
...
[Test]  100% (157 of 157) |#########################################################################################| Elapsed Time: 0:00:02 Time:  0:00:02
2020-08-26 13:50:42,719 - shrinker.py:104 - INFO - Original model's Acc: 80.37, Size: 6.476016 MB, Sparsity: 19.66 %
[Test]  100% (157 of 157) |#########################################################################################| Elapsed Time: 0:00:02 Time:  0:00:02
2020-08-26 13:50:45,781 - shrinker.py:118 - INFO - Shrinked model's Acc: 80.37, Size: 4.141713 MB, Params: 0.51 M
2020-08-26 13:50:45,884 - shrinker.py:125 - INFO - Saved shrinked model as save/checkpoint/200826_135036/shrinked_model.pth
2020-08-26 13:50:45,884 - shrinker.py:128 - INFO - Load a shrinked model from save/checkpoint/200826_135036/shrinked_model.pth
[Test]  100% (157 of 157) |#########################################################################################| Elapsed Time: 0:00:02 Time:  0:00:02
2020-08-26 13:50:48,759 - shrinker.py:137 - INFO - Loaded model's Acc: 80.37, Size: 4.141713 MB, Params: 0.51 M
```

**Comment by Curt-Park** [comment]
Slim 35.57% pruned

parameters

```bash
2020-08-26 13:52:58,946 - trainer.py:71 - INFO - Created a model densenet with 0.78M params
...
2020-08-26 13:52:59,969 - shrinker.py:92 - INFO - Initialize the model from the checkpoint save/test/slim_35_57_pruned/298_79_07.pth.tar
[Test]  100% (157 of 157) |#########################################################################################| Elapsed Time: 0:00:02 Time:  0:00:02
2020-08-26 13:53:03,100 - shrinker.py:104 - INFO - Original model's Acc: 79.07, Size: 6.476016 MB, Sparsity: 35.57 %
[Test]  100% (157 of 157) |#########################################################################################| Elapsed Time: 0:00:02 Time:  0:00:02
2020-08-26 13:53:06,114 - shrinker.py:118 - INFO - Shrinked model's Acc: 79.07, Size: 2.851149 MB, Params: 0.35 M
2020-08-26 13:53:06,178 - shrinker.py:125 - INFO - Saved shrinked model as save/checkpoint/200826_135257/shrinked_model.pth
2020-08-26 13:53:06,178 - shrinker.py:128 - INFO - Load a shrinked model from save/checkpoint/200826_135257/shrinked_model.pth
[Test]  100% (157 of 157) |#########################################################################################| Elapsed Time: 0:00:02 Time:  0:00:02
2020-08-26 13:53:09,048 - shrinker.py:137 - INFO - Loaded model's Acc: 79.07, Size: 2.851149 MB, Params: 0.35 M

```

**Comment by Curt-Park** [comment]
DenseNet small's static quantization result:
```bash
$ python quantize.py --config config/quantize/cifar100/densenet_small.py --checkpoint save/test/densenet_small/296_81_20.pth.tar --static --check-acc
2020-08-26 13:57:02,559 - config_validator.py:44 - INFO - [Config]      SEED: 777       AUG_TRAIN: randaugment_train_cifar100   AUG_TRAIN_PARAMS: {'n_select': 2, 'level': None}  AUG_TEST: simple_augment_test_cifar100  CUTMIX: {'beta': 1, 'prob': 0.5}        DATASET: CIFAR100       MODEL_NAME: quant_densenetMODEL_PARAMS: {'num_classes': 100, 'inplanes': 24, 'growthRate': 12, 'compressionRate': 2, 'block_configs': (16, 16, 16)}       CRITERION: CrossEntropy CRITERION_PARAMS: {'num_classes': 100, 'label_smoothing': 0.1}    LR_SCHEDULER: WarmupCosineLR    LR_SCHEDULER_PARAMS: {'warmup_epochs': 0, 'start_lr': 0.0001}     BATCH_SIZE: 64  LR: 0.0001      MOMENTUM: 0.9   WEIGHT_DECAY: 0.0001    EPOCHS: 5       N_WORKERS: 16
2020-08-26 13:57:02,595 - trainer.py:71 - INFO - Created a model quant_densenet with 0.78M params
2020-08-26 13:57:02,595 - trainer.py:74 - INFO - Setup train configuration
Files already downloaded and verified
2020-08-26 13:57:03,429 - trainer.py:97 - INFO - Datasets prepared
2020-08-26 13:57:03,429 - trainer.py:109 - INFO - Dataloader prepared
2020-08-26 13:57:03,432 - quantizer.py:137 - INFO - Load weights from the checkpoint save/test/densenet_small/296_81_20.pth.tar
2020-08-26 13:57:03,464 - quantizer.py:148 - INFO - Dummy prunning to load pruned weights
2020-08-26 13:57:03,540 - quantizer.py:152 - INFO - Initialized weights
2020-08-26 13:57:03,541 - quantizer.py:158 - INFO - Get masks and remove prunning reparameterization for prepare_qat
2020-08-26 13:57:05,275 - quantizer.py:87 - INFO - Acc: 81.2 %  Size: 3.286695 MB
2020-08-26 13:57:05,344 - quantizer.py:95 - INFO - Post Training Static Quantization: Run calibration
[Test]  100% (157 of 157) |#########################################################################################| Elapsed Time: 0:02:40 Time:  0:02:40
2020-08-26 13:59:47,555 - quantizer.py:117 - INFO - Acc: 81.03 %        Size: 0.974913 MB
```

**Comment by Curt-Park** [comment]
DeseNet small's QAT result (5 epochs):

```bash
$ python quantize.py --config config/quantize/cifar100/densenet_small.py --checkpoint save/test/densenet_small/296_81_20.pth.tar --check-acc
...
2020-08-26 14:06:46,855 - trainer.py:71 - INFO - Created a model quant_densenet with 0.78M params
...
2020-08-26 14:06:49,506 - quantizer.py:87 - INFO - Acc: 81.2 %  Size: 3.286695 MB
Ongoing..
```

**Comment by Curt-Park** [comment]
@all-contributors please add @Curt-Park for code

**Comment by Curt-Park** [comment]
@all-contributors please add Hoonyyhoon  for  code

**Comment by Hoonyyhoon** [comment]
Lash hurrah! Good work! @Curt-Park

**Pull request merged**
